format = '$status$directory$git_branch$git_status'
add_newline = false

[git_branch]
format = '[(git:\([$branch](bold red)\) )](bold blue)'

[git_status]
format = '[($all_status )]($style)'

[status]
disabled = false
symbol = '➜'
success_symbol = '[➜](bold green)'
not_executable_symbol = '➜'
not_found_symbol = '➜'
sigint_symbol = '➜'
style = 'bold red'
format = '[$symbol]($style)  '
map_symbol = true